### ISSUE TITLE
Use Crowdin for localization

### ISSUE THREAD

**Issue by jarvislin** [xserver-inc/cocoon#95]
Hi there!

I would like to recommend using [Crowdin](https://crowdin.com/) to manage the localization files so translators can easily translate the texts. (GitHub is more suitable for developers.)

The [Free plan](https://crowdin.com/pricing#crowdin-pricing-key-features) is enough to use at the moment. And it provides [GitHub integration](https://support.crowdin.com/github-integration/) so it will sync the localization files to Crowdin automatically.

Thanks for developing this awesome WordPress theme.

**Comment by vic322** [comment]
Hi jarvislin

I'll try Crowdin and see if it works well with this project.

**Comment by vic322** [comment]
@jarvislin

Sorry for not updating for a long time.
I hope you are still here.

I've created a test project.
https://crowdin.com/project/wp-cocoon

Since xserver did not allow us to integrate github with crowdin, I'm using my fork repository.
I will make a pull request to this repo once the translation is updated.

**Comment by jarvislin** [comment]
No problem, thanks for letting me know.
